# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/koola/OneDrive/Desktop/Folders/203 Lab/Lab 6/Lab6_Sevenseg/Lab6_Sevenseg.srcs/constrs_1/new/7_seg.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
